

keys <- bind_rows(
  # --- SHEET A1 ---
  key_row("total_owed_prevention_and_relief", "A1", "G", c("assessed as owed a duty Total owed prevention or relief duty"),
          label = "Assessed as owed a duty: total owed prevention or relief duty"),
  key_row("total_initial_assessments", "A1", "E", c("total initial assessments1,2,6"),
          label = "Total initial assessments"),
  key_row("threatened with homelessness", "A1", "H", c("assessed as owed a duty Threatened with homelessness within 56 days - Prevention duty owed"),
          label = "Assessed as owed a duty: threatened with homelessness within 56 days (prevention duty owed)"),
  key_row("relief_duty_owed", "A1", "J", c("assessed as owed a duty Homeless - Relief duty owed"),
          label = "Assessed as owed a duty: homeless (relief duty owed)"),
  key_row("prevention_per_000", "A1", "Q", c("Households assessed as threatened with homelessness per (000s)"),
          label = "Households assessed as threatened with homelessness per (000s)"),
  key_row("relief_per_000", "A1", "R", c("Households assessed as homeless per (000s)"),
          label = "Households assessed as homeless per (000s)"),
  
  # --- SHEET A2P ---
  key_row("total_owed_prevention_duty", "A2P", "E", c("Total owed a prevention duty"),
          label = "Total owed a prevention duty"),
  key_row("total_end_of_ast", "A2P", "G", c("End of assured shorthold (AST) private rented tenancy, due to.. Total end of AST"),
          label = "End of AST private rented tenancy: total end of AST"),
  key_row("rent_arrears_tenant_difficulty_budgeting", "A2P", "I", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears, due to Tenant difficulty budgeting or making other payment(s)"),
          label = "End of AST: rent arrears (tenant difficulty budgeting / other payments)"),
  key_row("rent_arrears_increase_in_rent", "A2P", "J", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears, due to Increase in rent"),
          label = "End of AST: rent arrears (increase in rent)"),
  key_row("rent_arrears_reduction_employment_income", "A2P", "K", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears, due to Reduction in employment income"),
          label = "End of AST: rent arrears (reduction in employment income)"),
  key_row("rent_arrears_changes_benefit_entitlement", "A2P", "L", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears, due to Changes in benefit entitlement"),
          label = "End of AST: rent arrears (changes in benefit entitlement)"),
  key_row("rent_arrears_change_personal_circumstances", "A2P", "M", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears, due to Change in personal circumstances"),
          label = "End of AST: rent arrears (change in personal circumstances)"),
  key_row("end_non_ast_private_rented_tenancy", "A2P", "AA", c("End of non-AST private rented tenancy"),
          label = "End of non-AST private rented tenancy"),
  key_row("family_friends_no_longer_willing", "A2P", "AB", c("Family or friends no longer willing or able to accommodate"),
          label = "Family or friends no longer willing or able to accommodate"),
  key_row("non_violent_relationship_breakdown_partner", "A2P", "AC", c("Non-violent relationship breakdown with partner"),
          label = "Non-violent relationship breakdown with partner"),
  key_row("total_domestic_abuse", "A2P", "AE", c("domestic abuse total domestic abuse"),
          label = "Domestic abuse: total domestic abuse"),
  key_row("other_violence_or_harassment", "A2P", "AJ", c("Other violence or harassment", "Other violence or harrassment"),
          label = "Other violence or harassment"),
  key_row("total_end_social_rented_tenancy", "A2P", "AL", c("End of social rented tenancy, due to.. Total end of social rented tenancy"),
          label = "End of social rented tenancy: total end of social rented tenancy"),
  key_row("total_evicted_supported_housing", "A2P", "AQ", c("Eviction from supported housing, due to.. Total evicted from supported housing"),
          label = "Eviction from supported housing: total evicted from supported housing"),
  key_row("total_departure_from_institution", "A2P", "AV", c("Departure from institution : Total Departure from institution"),
          label = "Departure from institution: total"),
  key_row("custody", "A2P", "AW", c("Departure from institution : Custody"),
          label = "Departure from institution: custody"),
  key_row("hospital_psychiatric", "A2P", "AX", c("Departure from institution : Hospital (psychiatric)"),
          label = "Departure from institution: hospital (psychiatric)"),
  key_row("hospital_general", "A2P", "AY", c("Departure from institution : Hospital (general)"),
          label = "Departure from institution: hospital (general)"),
  key_row("looked_after_child_placement", "A2P", "AZ", c("Departure from institution : Looked after child placement"),
          label = "Departure from institution: looked after child placement"),
  key_row("leave_home_office_asylum_support", "A2P", "BC", c("Required to leave accommodation provided by Home Office as asylum support"),
          label = "Required to leave Home Office asylum support accommodation"),
  key_row("home_no_longer_suitable_disability_ill_health", "A2P", "BE", c("Home no longer suitable - disability / ill health"),
          label = "Home no longer suitable: disability / ill health"),
  key_row("test_column", "A2P", "U", c("TEST COLUMN"),
          label = "TEST COLUMN"),
  key_row("other_reasons_not_known", "A2P", "BF", c("Other reasons / not known"),
          label = "Other reasons / not known"),
  
  # --- SHEET A2R ---
  key_row("relief_total_owed", "A2R", "E", c("Total owed a relief duty"),
          label = "Total owed a relief duty"),
  key_row("relief_total_end_of_ast", "A2R", "G", c("End of assured shorthold (AST) private rented tenancy, due to.. Total end of AST"),
          label = "End of AST private rented tenancy: total end of AST"),
  key_row("relief_rent_arrears_budgeting", "A2R", "I", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears: Tenant difficulty budgeting"),
          label = "End of AST: rent arrears (tenant difficulty budgeting)"),
  key_row("relief_rent_arrears_increase", "A2R", "J", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears: Increase in rent"),
          label = "End of AST: rent arrears (increase in rent)"),
  key_row("relief_rent_arrears_income_reduction", "A2R", "K", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears: Reduction in employment income"),
          label = "End of AST: rent arrears (reduction in employment income)"),
  key_row("relief_rent_arrears_benefit_change", "A2R", "L", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears: Changes in benefit entitlement"),
          label = "End of AST: rent arrears (changes in benefit entitlement)"),
  key_row("relief_rent_arrears_personal_circs", "A2R", "M", c("End of assured shorthold (AST) private rented tenancy, due to.. Rent Arrears: Change in personal circumstances"),
          label = "End of AST: rent arrears (change in personal circumstances)"),
  key_row("relief_end_non_ast", "A2R", "AA", c("End of non-AST private rented tenancy"),
          label = "End of non-AST private rented tenancy"),
  key_row("relief_family_friends_unwilling", "A2R", "AB", c("Family or friends no longer willing or able to accommodate"),
          label = "Family or friends no longer willing or able to accommodate"),
  key_row("relief_relationship_breakdown", "A2R", "AC", c("Non-violent relationship breakdown with partner"),
          label = "Non-violent relationship breakdown with partner"),
  key_row("relief_domestic_abuse", "A2R", "AE", c("Domestic Abuse Total Domestic Abuse"),
          label = "Domestic abuse: total domestic abuse"),
  key_row("relief_other_violence", "A2R", "AJ", c("Other violence or harassment", "Other violence or harrassment"),
          label = "Other violence or harassment"),
  key_row("relief_social_tenancy_end", "A2R", "AL", c("End of social rented tenancy, due to.. Total end of social rented tenancy"),
          label = "End of social rented tenancy: total end of social rented tenancy"),
  key_row("relief_evicted_supported", "A2R", "AQ", c("Eviction from supported housing, due to.. Total evicted from supported housing"),
          label = "Eviction from supported housing: total evicted from supported housing"),
  key_row("relief_departure_institution", "A2R", "AV", c("Departure from institution : Total Departure from institution"),
          label = "Departure from institution: total"),
  key_row("relief_custody", "A2R", "AW", c("Departure from institution : Custody"),
          label = "Departure from institution: custody"),
  key_row("relief_hospital_psych", "A2R", "AX", c("Departure from institution : Hospital (psychiatric)"),
          label = "Departure from institution: hospital (psychiatric)"),
  key_row("relief_hospital_gen", "A2R", "AY", c("Departure from institution : Hospital (general)"),
          label = "Departure from institution: hospital (general)"),
  key_row("relief_looked_after_child", "A2R", "AZ", c("Departure from institution : Looked after child placement"),
          label = "Departure from institution: looked after child placement"),
  key_row("relief_home_office_asylum", "A2R", "BC", c("Required to leave accommodation provided by Home Office as asylum support"),
          label = "Required to leave Home Office asylum support accommodation"),
  key_row("relief_home_unsuitable_health", "A2R", "BE", c("Home no longer suitable - disability / ill health"),
          label = "Home no longer suitable: disability / ill health"),
  key_row("relief_other_reasons", "A2R", "BF", c("Other reasons / not known"),
          label = "Other reasons / not known"),
  
  # --- SHEET A5P ---
  key_row("a5p_prevention_total_owed", "A5P", "E", c("Total owed a prevention duty"),
          label = "Total owed a prevention duty"),
  key_row("a5p_single_dep_male", "A5P", "H", c("Single parent with dependent children - Male"),
          label = "Single parent with dependent children: male"),
  key_row("a5p_single_dep_female", "A5P", "J", c("Single parent with dependent children - Female"),
          label = "Single parent with dependent children: female"),
  key_row("a5p_single_dep_other", "A5P", "L", c("Single parent with dependent children - Other / sex not known"),
          label = "Single parent with dependent children: other / sex not known"),
  key_row("a5p_single_adult_male", "A5P", "O", c("Single adult - Male"),
          label = "Single adult: male"),
  key_row("a5p_single_adult_female", "A5P", "Q", c("Single adult - Female"),
          label = "Single adult: female"),
  key_row("a5p_single_adult_other", "A5P", "S", c("Single adult - Other / sex not known"),
          label = "Single adult: other / sex not known"),
  key_row("a5p_couple_with_dependent_children", "A5P", "V", c("Couple Two adults with dependent children"),
          label = "Couple (two adults) with dependent children"),
  key_row("a5p_couple_without_dependent_children", "A5P", "X", c("Couple Two adults without dependent children"),
          label = "Couple (two adults) without dependent children"),
  key_row("a5p_3plus_with_dependent_children", "A5P", "Z", c("three or more adults with dependent children"),
          label = "Three or more adults with dependent children"),
  key_row("a5p_3plus_without_dependent_children", "A5P", "AB", c("three or more adults without dependent children"),
          label = "Three or more adults without dependent children"),
  key_row("a5p_not_known", "A5P", "AD", c("Not known"),
          label = "Not known"),
  
  # --- SHEET A5R ---
  key_row("a5r_total_owed_relief_prevention_duty", "A5R", "E", c("Total owed a relief duty"),
          label = "Total owed a relief duty"),
  key_row("a5r_single_dep_male", "A5R", "H", c("Single parent with dependent children - Male"),
          label = "Single parent with dependent children: male"),
  key_row("a5r_single_dep_female", "A5R", "J", c("Single parent with dependent children - Female"),
          label = "Single parent with dependent children: female"),
  key_row("a5r_single_dep_other", "A5R", "L", c("Single parent with dependent children - Other / not known"),
          label = "Single parent with dependent children: other / not known"),
  key_row("a5r_single_adult_male", "A5R", "O", c("Single adult - Male"),
          label = "Single adult: male"),
  key_row("a5r_single_adult_female", "A5R", "Q", c("Single adult - Female"),
          label = "Single adult: female"),
  key_row("a5r_single_adult_other", "A5R", "S", c("Single adult - Other / sex not known"),
          label = "Single adult: other / sex not known"),
  key_row("a5r_couple_with_dependent_children", "A5R", "V", c("Couple Two adults with dependent children"),
          label = "Couple (two adults) with dependent children"),
  key_row("a5r_couple_without_dependent_children", "A5R", "X", c("Couple Two adults without dependent children"),
          label = "Couple (two adults) without dependent children"),
  key_row("a5r_3plus_with_dependent_children", "A5R", "Z", c("three or more adults with dependent children"),
          label = "Three or more adults with dependent children"),
  key_row("a5r_3plus_without_dependent_children", "A5R", "AB", c("three or more adults without dependent children"),
          label = "Three or more adults without dependent children"),
  key_row("a5r_not_known", "A5R", "AD", c("Not known"),
          label = "Not known"),
  
  # --- SHEET A6 ---
  key_row("a6_total_owed_relief_prevention_duty", "A6", "E", c("Total owed a prevention or relief duty"),
          label = "Total owed a prevention or relief duty"),
  key_row("a6_16_17", "A6", "G", c("16-17"),
          label = "Age 16-17"),
  key_row("a6_18_24", "A6", "I", c("18-24"),
          label = "Age 18-24"),
  key_row("a6_25_34", "A6", "K", c("25-34"),
          label = "Age 25-34"),
  key_row("a6_35_44", "A6", "M", c("35-44"),
          label = "Age 35-44"),
  key_row("a6_45_54", "A6", "O", c("45-54"),
          label = "Age 45-54"),
  key_row("a6_55_64", "A6", "Q", c("55-64"),
          label = "Age 55-64"),
  key_row("a6_65_74", "A6", "S", c("65-74"),
          label = "Age 65-74"),
  key_row("a6_75_plus", "A6", "U", c("75 plus", "75+"),
          label = "Age 75+"),
  key_row("a6_not_known", "A6", "W", c("Not known"),
          label = "Not known"),
  
  # --- SHEET A8 ---
  key_row("a8_total_owed_relief_prevention_duty", "A8", "E", c("Total owed a prevention or relief duty"),
          label = "Total owed a prevention or relief duty"),
  key_row("a8_white", "A8", "H", c("White total"),
          label = "Ethnicity: White (total)"),
  key_row("a8_black", "A8", "S", c("Black / African / Caribbean / Black British total"),
          label = "Ethnicity: Black / African / Caribbean / Black British (total)"),
  key_row("a8_asian", "A8", "AB", c("Asian / Asian British total"),
          label = "Ethnicity: Asian / Asian British (total)"),
  key_row("a8_mixed", "A8", "AO", c("Mixed / Multiple ethnic groups total"),
          label = "Ethnicity: Mixed / multiple ethnic groups (total)"),
  key_row("a8_other", "A8", "AZ", c("Other ethnic group total"),
          label = "Ethnicity: Other ethnic group (total)"),
  key_row("not_known", "A8", "BG", c("Not known"),
          label = "Ethnicity: Not known"),
  
  # --- SHEET P1 ---
  key_row("p1_total_ended", "P1", "E", c("Total number of households whose prevention duty ended"),
          label = "Total households whose prevention duty ended"),
  key_row("p1_secured_acc", "P1", "G", c("Secured accommodation for 6+ months Total secured accommodation"),
          label = "Secured accommodation for 6+ months (total secured accommodation)"),
  key_row("p1_homeless_intentional", "P1", "K", c("Homeless (including intentionally homeless)"),
          label = "Homeless (including intentionally homeless)"),
  key_row("p1_refused_suitable", "P1", "L", c("Refused suitable accommodation offer"),
          label = "Refused suitable accommodation offer"),
  key_row("p1_refused_cooperate", "P1", "M", c("Refused to cooperate"),
          label = "Refused to cooperate"),
  key_row("p1_contact_lost", "P1", "N", c("Contact lost"),
          label = "Contact lost"),
  key_row("p1_withdrew_deceased", "P1", "P", c("Withdrew application / applicant deceased Total withdrew / deceased"),
          label = "Withdrew application / applicant deceased (total withdrew / deceased)"),
  key_row("p1_56_days_no_action", "P1", "U", c("56 days elapsed and no further action"),
          label = "56 days elapsed and no further action"),
  key_row("p1_no_longer_eligible", "P1", "V", c("No longer eligible"),
          label = "No longer eligible"),
  key_row("p1_not_known", "P1", "W", c("Not known"),
          label = "Not known"),
  
  # --- SHEET P3 ---
  key_row("p3_total_secured", "P3", "E", c("Total number of households where prevention duty ended with accommodation secured"),
          label = "Total households where prevention duty ended with accommodation secured"),
  key_row("p3_secured_by_la", "P3", "F", c("Accommodation secured by local authority or organisation delivering housing options service"),
          label = "Accommodation secured by local authority / housing options service"),
  key_row("p3_helped_financial", "P3", "G", c("Helped to secure accommodation found by applicant, with financial payment"),
          label = "Helped to secure accommodation found by applicant (with financial payment)"),
  key_row("p3_helped_no_financial", "P3", "H", c("Helped to secure accommodation found by applicant, without financial payment"),
          label = "Helped to secure accommodation found by applicant (without financial payment)"),
  key_row("p3_supported_housing", "P3", "I", c("Supported housing provided"),
          label = "Supported housing provided"),
  key_row("p3_mediation_family", "P3", "J", c("Negotiation / mediation work to secure return to family or friend"),
          label = "Negotiation/mediation to secure return to family or friend"),
  key_row("p3_mediation_eviction", "P3", "K", c("Negotiation / mediation / advocacy work to prevent eviction / repossession"),
          label = "Negotiation/mediation/advocacy to prevent eviction / repossession"),
  key_row("p3_dhp", "P3", "L", c("Discretionary Housing Payment to reduce shortfall"),
          label = "Discretionary Housing Payment to reduce shortfall"),
  key_row("p3_other_financial", "P3", "M", c("Other financial payments to reduce arrears"),
          label = "Other financial payments to reduce arrears"),
  key_row("p3_other_activity", "P3", "N", c("Other"),
          label = "Other"),
  key_row("p3_no_activity_advice", "P3", "O", c("No activity - advice and information provided"),
          label = "No activity (advice and information provided)"),
  
  # --- SHEET R1 ---
  key_row("r1_total_ended", "R1", "E", c("Total number of households whose relief duty ended"),
          label = "Total households whose relief duty ended"),
  key_row("r1_secured_6_months", "R1", "F", c("Secured accommodation for 6+ months"),
          label = "Secured accommodation for 6+ months"),
  key_row("r1_56_days_elapsed", "R1", "G", c("56 days elapsed"),
          label = "56 days elapsed"),
  key_row("r1_local_conn_referral", "R1", "H", c("Local connection referral accepted by other LA"),
          label = "Local connection referral accepted by other LA"),
  key_row("r1_intentional_homeless", "R1", "I", c("Intentionally homeless from accommodation provided"),
          label = "Intentionally homeless from accommodation provided"),
  key_row("r1_refused_final_acc", "R1", "J", c("Refused final accommodation"),
          label = "Refused final accommodation"),
  key_row("r1_refused_cooperate", "R1", "K", c("Notice served due to refusal to cooperate"),
          label = "Notice served due to refusal to cooperate"),
  key_row("r1_contact_lost", "R1", "L", c("Contact lost"),
          label = "Contact lost"),
  key_row("r1_withdrew_deceased", "R1", "N", c("Withdrew application / applicant deceased Total withdrew / deceased"),
          label = "Withdrew application / applicant deceased (total withdrew / deceased)"),
  key_row("r1_no_longer_eligible", "R1", "S", c("No longer eligible"),
          label = "No longer eligible"),
  key_row("r1_not_known", "R1", "T", c("Not known"),
          label = "Not known"),
  
  # --- SHEET R3 ---
  key_row("r3_total_secured", "R3", "E", c("Total number of households where relief duty ended with accommodation secured"),
          label = "Total households where relief duty ended with accommodation secured"),
  key_row("r3_secured_by_la", "R3", "F", c("Accommodation secured by local authority or organisation delivering housing options service"),
          label = "Accommodation secured by local authority / housing options service"),
  key_row("r3_helped_financial", "R3", "G", c("Helped to secure accommodation found by applicant, with financial payment"),
          label = "Helped to secure accommodation found by applicant (with financial payment)"),
  key_row("r3_helped_no_financial", "R3", "H", c("Helped to secure accommodation found by applicant, without financial payment"),
          label = "Helped to secure accommodation found by applicant (without financial payment)"),
  key_row("r3_supported_housing", "R3", "I", c("Supported housing provided"),
          label = "Supported housing provided"),
  key_row("r3_other_activity", "R3", "J", c("Other activity through which accommodation secured"),
          label = "Other activity through which accommodation secured"),
  key_row("r3_no_activity", "R3", "K", c("No activity"),
          label = "No activity"),
  
  # --- SHEET MD1 ---
  key_row("md1_total_main_duty_decisions", "MD1", "E", c("Total main duty decisions for eligible households"),
          label = "Total main duty decisions (eligible households)"),
  key_row("md1_homeless_priority_need_unint", "MD1", "F", c("Homeless + priority need + unintentionally homeless (acceptance)"),
          label = "Homeless + priority need + unintentionally homeless (acceptance)"),
  key_row("md1_homeless_priority_need_int", "MD1", "G", c("Homeless + priority need + intentionally homeless"),
          label = "Homeless + priority need + intentionally homeless"),
  key_row("md1_homeless_no_priority", "MD1", "H", c("Homeless + no priority need"),
          label = "Homeless + no priority need"),
  key_row("md1_not_homeless", "MD1", "I", c("Not homeless"),
          label = "Not homeless"),
  
  # --- SHEET MD2 ---
  key_row("md2_total_main_duty_ended", "MD2", "E", c("Total households whose main duty ended"),
          label = "Total households whose main duty ended"),
  key_row("md2_housing_act_accepted", "MD2", "G", c("Housing Act 1996 Pt6 social housing offer accepted"),
          label = "Housing Act 1996 Pt 6 social housing offer accepted"),
  key_row("md2_housing_act_refused", "MD2", "H", c("Housing Act 1996 Pt6 social housing offer refused"),
          label = "Housing Act 1996 Pt 6 social housing offer refused"),
  key_row("md2_private_sector_accepted", "MD2", "J", c("Private rented sector offer accepted"),
          label = "Private rented sector offer accepted"),
  key_row("md2_private_sector_refused", "MD2", "K", c("Private rented sector offer refused"),
          label = "Private rented sector offer refused"),
  key_row("md2_refused_ta_offer", "MD2", "M", c("Refused suitable TA offer, withdrew or lost contact"),
          label = "Refused suitable TA offer / withdrew / lost contact"),
  key_row("md2_homeless_no_eligibility", "MD2", "N", c("Ceased to be eligible"),
          label = "Ceased to be eligible"),
  key_row("md2_intentionally_homeless", "MD2", "O", c("Became intentionally homeless from TA"),
          label = "Became intentionally homeless from TA"),
  key_row("md2_voluntarily", "MD2", "P", c("Voluntarily ceased to occupy TA"),
          label = "Voluntarily ceased to occupy TA"),
  key_row("md2_not_known", "MD2", "Q", c("Not known"),
          label = "Not known"),
  
  # --- SHEET TA1 ---
  key_row("ta_total_households", "TA1", "E", c("Total number of households in TA"),
          label = "Total households in temporary accommodation (TA)"),
  key_row("ta_per_000", "TA1", "G", c("Total number of households in TA per (000s)"),
          label = "Households in TA per (000s)"),
  key_row("ta_with_children", "TA1", "H", c("Total number of households in TA with children"),
          label = "Households in TA with children"),
  key_row("ta_total_children", "TA1", "I", c("Total number of children in TA"),
          label = "Total children in TA"),
  key_row("ta_bb_total", "TA1", "K", c("Bed and Breakfast Hotels (including shared annexes) - Total number of households"),
          label = "B&B: total households"),
  key_row("ta_bb_children", "TA1", "L", c("Bed and Breakfast Hotels (including shared annexes) - Total with children"),
          label = "B&B: households with children"),
  key_row("ta_bb_over_6wks", "TA1", "M", c("Bed and Breakfast hotels (including shared annexes) - Total with children > 6 weeks"),
          label = "B&B: households with children > 6 weeks"),
  key_row("ta_bb_over_6wks_pending", "TA1", "N", c("Bed and Breakfast hotels (including shared annexes) - Total with children > 6 weeks pending review"),
          label = "B&B: households with children > 6 weeks pending review"),
  key_row("ta_bb_16_17_applicant", "TA1", "O", c("Bed and Breakfast hotels (including shared annexes) - Total with 16/17-year-old applicant"),
          label = "B&B: households with 16/17-year-old applicant"),
  key_row("ta_nightly_paid_total", "TA1", "Q", c("Nightly paid, privately managed accommodation, self-contained total number of households"),
          label = "Nightly paid (privately managed, self-contained): total households"),
  key_row("ta_nightly_paid_children", "TA1", "R", c("Nightly paid, privately managed accommodation, self-contained total with children"),
          label = "Nightly paid (privately managed, self-contained): households with children"),
  key_row("ta_hostel_total", "TA1", "T", c("Hostels (including reception centres, emergency units and refuges) total number of households"),
          label = "Hostels (incl reception/emergency/refuges): total households"),
  key_row("ta_hostel_children", "TA1", "U", c("Hostels (including reception centres, emergency units and refuges) total with children"),
          label = "Hostels (incl reception/emergency/refuges): households with children"),
  key_row("ta_private_leased_total", "TA1", "W", c("Private sector accommodation leased by your authority or leased or managed by a registered provider total number of households"),
          label = "Private sector leased (LA/RP): total households"),
  key_row("ta_private_leased_children", "TA1", "X", c("Private sector accommodation leased by your authority or leased or managed by a registered provider total with children"),
          label = "Private sector leased (LA/RP): households with children"),
  key_row("ta_la_ha_stock_total", "TA1", "Z", c("Local authority or Housing association (LA/HA) stock total number of households"),
          label = "LA/HA stock: total households"),
  key_row("ta_la_ha_stock_children", "TA1", "AA", c("Local authority or Housing association (LA/HA) stock total with children"),
          label = "LA/HA stock: households with children"),
  key_row("ta_other_type_total", "TA1", "AC", c("Any other type of temporary accommodation (including private landlord and not known) total number of households"),
          label = "Other TA types (incl private landlord / not known): total households"),
  key_row("ta_other_type_children", "TA1", "AD", c("Any other type of temporary accommodation (including private landlord and not known) total with children"),
          label = "Other TA types (incl private landlord / not known): households with children"),
  key_row("ta_another_la_district", "TA1", "AF", c("In TA in another local authority district"),
          label = "In TA in another local authority district"),
  key_row("ta_duty_owed_no_acc_total", "TA1", "AH", c("Duty owed, no accommodation secured total number of households"),
          label = "Duty owed, no accommodation secured: total households"),
  key_row("ta_duty_owed_no_acc_children", "TA1", "AI", c("Duty owed, no accommodation secured total with children"),
          label = "Duty owed, no accommodation secured: households with children")
) %>%
  mutate(
    expected_excel_col = map_chr(expected_excel_cols, ~ paste(.x, collapse = "+")),
    is_group           = map_lgl(expected_excel_cols, ~ length(.x) > 1)
  )